# Mistral AI
MISTRAL_MODEL="ministral-8b-2410"
MISTRAL_API_KEY="879bTzUNjAUkjb6HP5QmWAaJTOrydqSG"

# CODEGPT
CODEGPT_API_KEY="sk-3b7c2d58-a492-4090-88ee-e0d98b6113b3"
CODEGPT_API_URL="https://api.codegpt.co/api/v1/"